"""Custom VaspCalculation for AIMD with POSCAR velocity support.

This module provides a VaspCalculation subclass that supports custom POSCAR files
with velocity blocks, enabling seamless AIMD continuation from previous stages.
"""

from aiida import orm
from aiida.common.datastructures import CalcInfo
from aiida.common.folders import Folder
from aiida_vasp.calcs.vasp import VaspCalculation
from aiida_vasp.workchains.v2.vasp import VaspWorkChain


class AimdVaspCalculation(VaspCalculation):
    """VaspCalculation subclass that supports custom POSCAR files.

    This enables passing POSCAR with velocity blocks from previous
    AIMD calculations for seamless MD continuation without thermal
    re-initialization.

    The key difference from VaspCalculation is the optional `poscar_file`
    input. If provided, this file overwrites the structure-based POSCAR
    after the standard file generation, preserving velocity information.

    Example:
        >>> from aiida.orm import SinglefileData
        >>> poscar_with_velocities = SinglefileData(file='/path/to/poscar')
        >>> builder = AimdVaspCalculation.get_builder()
        >>> builder.structure = structure
        >>> builder.poscar_file = poscar_with_velocities
        >>> ...
    """

    @classmethod
    def define(cls, spec):
        """Define the process specification."""
        super().define(spec)
        spec.input(
            'poscar_file',
            valid_type=orm.SinglefileData,
            required=False,
            help='Custom POSCAR file content (overrides structure-based generation). '
                 'Use this to pass a POSCAR with velocity blocks from previous AIMD.'
        )

    def prepare_for_submission(self, folder: Folder) -> CalcInfo:
        """Prepare the calculation for submission.

        Calls the parent prepare_for_submission, then overwrites the POSCAR
        file if a custom poscar_file input is provided. The custom POSCAR
        will replace any structure-based POSCAR generated by the parent.

        Args:
            folder: The sandbox folder for input files.

        Returns:
            CalcInfo with calculation metadata.
        """
        from io import BytesIO

        # Call parent to generate standard files (including POSCAR from structure)
        calcinfo = super().prepare_for_submission(folder)

        # If custom POSCAR is provided, overwrite the structure-based POSCAR
        # by writing directly to the folder. This ensures velocities are preserved.
        if 'poscar_file' in self.inputs:
            poscar_node = self.inputs.poscar_file
            # Read the custom POSCAR content from the SinglefileData node
            with poscar_node.open(poscar_node.filename, 'r') as f:
                poscar_content = f.read()
            # Write directly to the folder to overwrite the generated POSCAR
            # This must happen AFTER super().prepare_for_submission() to override it
            # Use BytesIO with utf-8 encoding as folder.create_file_from_filelike expects bytes
            folder.create_file_from_filelike(BytesIO(poscar_content.encode('utf-8')), 'POSCAR')

        return calcinfo


class AimdVaspWorkChain(VaspWorkChain):
    """VaspWorkChain subclass that uses AimdVaspCalculation.

    This WorkChain provides the same functionality as VaspWorkChain but
    uses AimdVaspCalculation as the underlying calculation class, enabling
    POSCAR files with velocity blocks.

    The poscar_file input is automatically exposed from AimdVaspCalculation.

    Example:
        >>> from aiida_workgraph import task
        >>> AimdVaspTask = task(AimdVaspWorkChain)
        >>> calc_task = wg.add_task(
        ...     AimdVaspTask,
        ...     structure=structure,
        ...     poscar_file=poscar_with_velocities,
        ...     ...
        ... )
    """

    # Use AimdVaspCalculation instead of VaspCalculation
    _process_class = AimdVaspCalculation

    @classmethod
    def define(cls, spec):
        """Define the process specification.

        Adds the poscar_file input to the WorkChain spec, ensuring it's properly
        exposed and passed through to the calculation.
        """
        super().define(spec)
        # Explicitly expose the poscar_file input from the calculation
        spec.input(
            'poscar_file',
            valid_type=orm.SinglefileData,
            required=False,
            help='Custom POSCAR file with velocities (for AIMD continuation). '
                 'Overwrites the structure-based POSCAR generation.'
        )
